backend/api/urls.py
from .auth import urls as urls_auth
from django.urls import path, include
from rest_framework.routers import SimpleRouter
from .views import AporteModelViewSet, WalletModelViewSet, ImportWalletCsv, PositionWallet, MovementModelViewSet

app_name = 'api'
router = SimpleRouter()
router.register("aporte", AporteModelViewSet)
router.register("wallet", WalletModelViewSet)
router.register("movement", MovementModelViewSet, basename='Moviment')


urlpatterns = [
    path('', include(router.urls)),
    path('csv',ImportWalletCsv.as_view()),
    path('position/<int:pk>',PositionWallet.as_view()),
    path('auth/', include(urls_auth)),

]

backend/aporte/urls.py
from django.urls import path

from .views import *

app_name = 'aporte'

urlpatterns = [
    path('',AporteListView.as_view(),name="aporte-list"),
    path('create',AporteCreateView.as_view(),name="aporte-create")
]

backend/aporte/models.py
from django.db import models
from functools import reduce
import datetime
# from datetime import timedelta
#from .selic import corrigir_selic
from decimal import Decimal
from selic.models import Selic
from wallet.models import Wallet
from django.db.models.signals import post_save
from django.dispatch import receiver
# Extend User: https://simpleisbetterthancomplex.com/tutorial/2016/07/22/how-to-extend-django-user-model.html


# Create your models here.
# CHORO?? hahaha  ??? Esquece... vamos para a parte de cadastrar o movimento de ativos na carteira.
# API.

#  Vamo fazer os modelos aqui depois refatoramos
class Grupo(models.Model):
    name = models.CharField(max_length=60, unique=True)

    def __str__(self):
        return "{}:{}".format(self.name, self.id)

class Aporte(models.Model):
    amount = models.DecimalField("Amount", max_digits=10, decimal_places=2)
    date = models.DateField("Date")
    final_date = models.DateField("Final Date",auto_now=False, auto_now_add=False,null=True, blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    grupo  = models.ForeignKey(Grupo,on_delete=models.CASCADE)

    def present_value(self, final_date=None):
        today = datetime.date.today()
        # print(today)
        data_final = ""
        if not self.final_date:
            final_date = today
        if final_date:
            data_final = final_date.strftime('%Y-%m-%d')
        else:
            if self.final_date > today:
                print("Aporte: {} - Data final {} maior que o dia de hoje {}.".format(self.amount, self.final_date, str(today.strftime('%d/%m/%Y')) ))
                data_final = today.strftime('%Y-%m-%d')
            else:
                data_final = (self.final_date - datetime.timedelta(days=1)).strftime('%Y-%m-%d')
        valor = self.amount
        # qs = Selic.objects.filter(date__range=[self.date, data_final]).values_list('daily_factor', flat=True)
        # fator = reduce((lambda x,y: x*y), qs)
        # selic_real = valor * fator
        #### SERA ??? # 
        selic_real = Selic.present_value(valor,self.date, data_final)
        #### talvez consumir a API?
        return round(selic_real,2)
        
    def __str__(self):
        return "Grupo: {}, Amount: {}, Data: {}".format(self.grupo, self.amount, self.date)

class TipoAtivo(Grupo):
    tipo = models.CharField(max_length=60, unique=True)

    def __str__(self):
        return "{}:{}".format(self.name, self.id)

class Ativo(Aporte):
    None





### Usuário
# Carteira:
#   Instituições.
#       Aportes em Instituições. # Valor do Aporte, Data do Aporte, {Valor Corrigido pela Selic, Valor Total}
#       Compra/Venda de Ativos:
#           Dinheiro na Instituição. # Saldo na conta da Instituição
#           Ações na Instituição. # Codigo, Data de Compra/Venda, Quantidade, Preço de Compra/Venda, Custos, Total, {Valor Atual, Valor Corrigido pela Selic}
#           Fundos Imobiliários (...). # Idem.
#           Fundos (...)
#           Tesouro Direto.
#           Duplicatas/Títulos. # 
#           Imóveis.
#           Forex.
#           Etc.


# Tipo de Aporte (Instituição, Ativos, Passivos, etc.)


### Tentando fazer uma API para retornar somente valor corrigido da SELIC:

# class Corrige(models.Model):
#     def __init__(self, amount, date, final_date):
#         self.amount = amount
#         self.date = date
#         self.final_date = final_date

#     def present_value(self, final_date=None):
#         today = datetime.date.today()
#         # print(today)
#         data_final = ""
#         if not self.final_date:
#             final_date = today
#         if final_date:
#             data_final = final_date.strftime('%Y-%m-%d')
#         else:
#             if self.final_date > today:
#                 print("Aporte: {} - Data final {} maior que o dia de hoje {}.".format(self.amount, self.final_date, str(today.strftime('%d/%m/%Y')) ))
#                 data_final = today.strftime('%Y-%m-%d')
#             else:
#                 data_final = (self.final_date - datetime.timedelta(days=1)).strftime('%Y-%m-%d')
#         valor = self.amount
#         qs = Selic.objects.filter(date__range=[self.date, data_final]).values_list('daily_factor', flat=True)
#         fator = reduce((lambda x,y: x*y), qs)
#         selic_real = valor * fator
#         return round(selic_real,2)


# Instrumento Pertence ao movimento vamos vazer o modelo de Instrumento
# Começa do zero num novo arquivo. # vai ficar melhor pra vc entender so esquece o que estar acima...
# Ok \o/
# Vou colar aqui os atributos que definimos la


# tckrSymb(Unique)
# crpnNm
# sgmtNm
# mktNm
# mctyCtgyNm
# ISIN
# corpGovnLvlNm
# cFICd

# nao sei o que eles queren dizer voce pode ir traduzindo ai :D
# Tudo é Texto?

# Cara na vdd eu sei mais ou menos... bem pra menos.. tudo texto. São coisas para identificar o Ativo Globalmente.
# tudo pode ser brano ou nulo?

# Não.. tckrSymb nao... mktNm tb não.
# OK

# Deixa eu abrir a tabela aqui... guenta hahah ...vo buscar cafe

# Cara, sgmtNm por exemplo, é uma classificação. Fica como string? pode ser se for muitas classificacoes 
# melhor ser uma tabela relacionada ex: sexo é F/M já profissao sao muitas, vamo fazer como string
#  Vamo pro moveimento


backend/aporte/forms.py
from django import forms 
from .models import Aporte


class AporteForm(forms.ModelForm):
    
    class Meta:
        model = Aporte
        fields = '__all__'
        widgets = {
            'date' : forms.TextInput(attrs={'type': 'date'}),
            'final_date':forms.TextInput(attrs={'type': 'date'}),
        }

backend/aporte/views.py
from django.shortcuts import render
from django.views.generic import ListView
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
# Create your views here.
from .models import Aporte#, Selic
from .forms import AporteForm
from selic.models import Selic


class AporteListView(ListView):
    model = Aporte
    template_name = "aportes.html"
    query_set = Aporte.objects.all()
    
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        #busca a Selic 
        Selic.update_me(self)
        return context
    

class AporteCreateView(CreateView):
    model = Aporte
    template_name = "aporte_form.html"
    form_class = AporteForm
    success_url = reverse_lazy('aporte:aporte-list')

backend/aporte/templates/aporte_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<h2>Aporte Create</h2>
<div class="container">
    <div class="row">
        <div class="col-sm-4">
            <form action="" method="post">
                {% csrf_token %}
                {{form|crispy}}
                <button class="btn btn-primary" type="submit">Save</button>
            </form>
        </div>
    </div>

</div>
{% endblock content %}

backend/aporte/templates/aportes.html
{% extends 'base.html' %}
{% block content %}

<h2>List Aportes</h2>
<div class="container">

    <table class="table table-bordered table-responsive" id="records_table">
        <thead>
            <tr>
                <td>Amount</td>
                <td>Date</td>
                <td>Final Date</td>
                <td>Amount + SELIC</td>
                <td> Aportado em</td>
            </tr>
        </thead>
        <tbody>
            {% for i in aporte_list %}
            <tr>
                <td>{{i.amount}}</td> 
                <td>{{i.date|date:'d/m/Y'}}</td> 
                <td>{{i.final_date|date:'d/m/Y'}}</td>
                <td>{{i.present_value}}</td>
                <td>{{i.grupo}}</td>

            </tr>
            {% endfor %}

            <!-- <button id="botaoView" class="btn-info navbar-btn"> Atualizar </button> -->
        </tbody>
    </table>
</div>

{% endblock content %}
 
{% block script %}
<script>
{% comment %} $('#botaoView').click(function() {
    $("#botaoView").attr("disabled", true);
    $('#botaoView').html("Atualizando...");
    const link = "http://127.0.0.1:8000/api/aporte/";
    $.ajax({
        url: link,
        type: 'GET',
        dataType: 'json',
  
      })
      .done(function(data) {
        console.log("success");
        console.log(data[0]["amount"]);
        var trHTML = '';
        $.each(data, function(index) {
            trHTML += '<tr><td>' + data[index].amount + '</td><td>' +
                                 data[index].date + '</td><td>' +
                                 data[index].final_date + '</td><td>' +
                                 data[index].selic + '</td><td>' + 
                                 data[index].grupo_name+ '</td></tr>';
        });
        $('#records_table').append(trHTML);
        $("#botaoView").attr("disabled", true);

        $('#botaoView').html("Atualizado");
        // var aportes = JSON.parse(data);
        // alert(aportes);
      })
      .fail(function() {
        console.log("error");
      })
      .always(function() {
        console.log("complete");
      });
  }); {% endcomment %}

</script>
  {% endblock script %}



backend/aporte/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <title>Aporte</title>
    <!-- Required meta tags -->

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body>

    <!-- Nav tabs -->
    <ul class="nav nav-pills" id="navbar">
        <li class="nav-item">
            <a href="{% url 'aporte:aporte-list' %}" class="nav-link active">Aportes</a>
        </li>

        <li class="nav-item">
            <a href="{% url 'aporte:aporte-create' %}" class="nav-link">New Aporte</a>
        </li>

    </ul>

    <!-- Tab panes -->
    <div class="container">
        {% block content %}

        {% endblock content %}
    </div>
    <!-- <script> -->
        <!-- $('#navbar a').click(e => { -->
            <!-- e.preventDefault(); -->
            <!-- $(this).tab('show'); -->
        <!-- }); -->
    <!-- </script> -->

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> -->
    <script src="https://code.jquery.com/jquery-3.4.0.js" integrity="sha256-DYZMCC8HTC+QDr5QNaIcfR7VSPtcISykd+6eSmBW5qo=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  {% block script %}

  {% endblock script %}
  </body>
</html>

backend/aporte/templates/corrige_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<h2>Aporte Create</h2>
<div class="container">
    <div class="row">
        <div class="col-sm-4">
            <form action="" method="post">
                {% csrf_token %}
                {{form|crispy}}
                <button class="btn btn-primary" type="submit">Save</button>
            </form>
        </div>
    </div>

</div>
{% endblock content %}